### ISSUE TITLE
add support latest docker version ( v1.13 )

### ISSUE THREAD

**Issue by nakatanakatana** [bargees/armhf-docker#1]

**Comment by ailispaw** [comment]
@nakatanakatana 
Thank you for opening this issue.
I can not build them now, because I'm in Japan and don't have the build environment.
I will build them after I get back US. It will be by the end of this month.
Thanks.

**Comment by ailispaw** [comment]
@nakatanakatana 

Just released v1.13.1
https://github.com/bargees/armhf-docker/tree/v1.13.1

**Comment by nakatanakatana** [comment]
Thanks!
